name: Django CI

on: [push, pull_request]

env:
  # Run tasks in the current thread, no need for workers in CI mode
  CELERY_TASK_ALWAYS_EAGER: True

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    services:
      postgres:
        image: postgres:10
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        make dev
        make envfile
    - name: Check Code Validation
      run: |
        make check
    - name: Create Database
      run: |
        createdb --encoding=utf-8 scancodeio
    - name: Run Tests
      run: |
        python manage.py test --settings=scancodeio.settings.base --verbosity=2 --noinput
